version: "3"
services:
  test_aly:
    build:
      ./
    command:
      python manage.py runserver 0.0.0.0:8080
    ports:
      - "80:8080"
    image:
      test_aly:latest
    environment:
      MYSQLLINK: mysql
      MYSQLUSER: root
      MYSQLPASSWD: abc1234
    depends_on:
      - mysql
  mysql:
    image:
      mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "abc1234"
    volumes:
      - /Volumes/mysql/data:/var/lib/mysql
