version: "3"
services:
  test_aly:
    build:
      ./
    command:
      python manage.py runserver 0.0.0.0:8080
    ports:
      - "80:8080"
    image:
      test_aly:latest
#    volumes:
#      - /volumes/sqlite:/code/db


#  test_crontab:
#    build:
#      ./
#    command:
#      python manage.py crontab add
#    image:
#      test_aly:latest

#
    environment:
      MYSQLLINK: mysql
      MYSQLUSER: root
      MYSQLPASSWD: abc1234
      REDISLINK: redis
    depends_on:
      - mysql
      - redis
  mysql:
    image:
      mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "abc1234"
    volumes:
      - /volumes/mysql/data:/var/lib/mysql

  redis:
    image:
      redis:5.0
    volumes:
      - /volumes/myredis/data:/data
    command:
      redis-server --appendonly yes