# Generated by Django 3.0.8 on 2020-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apicase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=128)),
                ('release', models.CharField(max_length=128)),
                ('modules', models.CharField(max_length=128)),
                ('casename', models.CharField(max_length=128)),
                ('casenumber', models.CharField(max_length=128)),
                ('caseurl', models.CharField(max_length=300)),
                ('caserequest', models.CharField(max_length=30)),
                ('caseheaders', models.CharField(max_length=300)),
                ('casebody', models.CharField(max_length=1000)),
                ('caseexpected', models.CharField(max_length=1000)),
                ('casedeliver', models.CharField(max_length=300)),
                ('casekey', models.CharField(max_length=300)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '接口用例',
                'verbose_name_plural': '接口用例',
                'ordering': ['-c_time'],
            },
        ),
    ]
