# Generated by Django 3.0.8 on 2020-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dcc', '0002_apilist'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportlist',
            fields=[
                ('reportname', models.CharField(max_length=128)),
                ('report', models.CharField(max_length=5000)),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'ordering': ['-c_time'],
            },
        ),
    ]
